/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;

import javax.swing.JDesktopPane;

/**
 *
 * @author Pablo Fellype
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/backlaranja.jpg"));
        Image image = icon.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItemAddUsuario = new javax.swing.JMenuItem();
        jMenuItemAltUsuario = new javax.swing.JMenuItem();
        jMenuItemExcUsuario = new javax.swing.JMenuItem();
        jMenuItemConUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemCadCliente = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItemAltCliente = new javax.swing.JMenuItem();
        jMenuItemExcCliente = new javax.swing.JMenuItem();
        jMenuItemConCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemAddVeiculo = new javax.swing.JMenuItem();
        jMenuItemCadastrarMarca = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItemAltVeiculo = new javax.swing.JMenuItem();
        jMenuItemExcVeiculo = new javax.swing.JMenuItem();
        jMenuItemConVeiculo = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAddLocacao = new javax.swing.JMenuItem();
        jMenuItemAltLocacao = new javax.swing.JMenuItem();
        jMenuItemExcLocacao = new javax.swing.JMenuItem();
        jMenuItemConLocacao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rent System");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1600, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 204, 0));
        jMenuBar1.setForeground(new java.awt.Color(255, 204, 0));

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_1.png"))); // NOI18N
        jMenu5.setText("Usuário");

        jMenuItemAddUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_add.png"))); // NOI18N
        jMenuItemAddUsuario.setText("Cadastrar");
        jMenu5.add(jMenuItemAddUsuario);

        jMenuItemAltUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_edit.png"))); // NOI18N
        jMenuItemAltUsuario.setText("Alterar");
        jMenu5.add(jMenuItemAltUsuario);

        jMenuItemExcUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user_delete.png"))); // NOI18N
        jMenuItemExcUsuario.setText("Excluir");
        jMenu5.add(jMenuItemExcUsuario);

        jMenuItemConUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        jMenuItemConUsuario.setText("Consultar");
        jMenu5.add(jMenuItemConUsuario);

        jMenuBar1.add(jMenu5);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_1.png"))); // NOI18N
        jMenu2.setText("Cliente");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_add.png"))); // NOI18N
        jMenu1.setText("Cadastrar");

        jMenuItemCadCliente.setText("Pessoa Física");
        jMenuItemCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemCadCliente);

        jMenuItem1.setText("Pessoa Jurídica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Motorista");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu2.add(jMenu1);

        jMenuItemAltCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_edit.png"))); // NOI18N
        jMenuItemAltCliente.setText("Aleterar");
        jMenu2.add(jMenuItemAltCliente);

        jMenuItemExcCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/group_delete.png"))); // NOI18N
        jMenuItemExcCliente.setText("Excluir");
        jMenu2.add(jMenuItemExcCliente);

        jMenuItemConCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        jMenuItemConCliente.setText("Consultar");
        jMenu2.add(jMenuItemConCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/veiculo.png"))); // NOI18N
        jMenu3.setText("Veículo");

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_add.png"))); // NOI18N
        jMenu6.setText("Cadastrar");

        jMenuItemAddVeiculo.setText("Veículo");
        jMenu6.add(jMenuItemAddVeiculo);

        jMenuItemCadastrarMarca.setText("Marca");
        jMenuItemCadastrarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarMarcaActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemCadastrarMarca);

        jMenuItem4.setText("Modelo");
        jMenu6.add(jMenuItem4);

        jMenuItem5.setText("Categoria");
        jMenu6.add(jMenuItem5);

        jMenu3.add(jMenu6);

        jMenuItemAltVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_edit.png"))); // NOI18N
        jMenuItemAltVeiculo.setText("Alterar");
        jMenu3.add(jMenuItemAltVeiculo);

        jMenuItemExcVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/car_delete.png"))); // NOI18N
        jMenuItemExcVeiculo.setText("Excluir");
        jMenu3.add(jMenuItemExcVeiculo);

        jMenuItemConVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        jMenuItemConVeiculo.setText("Consultar");
        jMenu3.add(jMenuItemConVeiculo);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chave.png"))); // NOI18N
        jMenu4.setText("Locação");

        jMenuItemAddLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/key_add.png"))); // NOI18N
        jMenuItemAddLocacao.setText("Cadastrar");
        jMenu4.add(jMenuItemAddLocacao);

        jMenuItemAltLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/page_edit.png"))); // NOI18N
        jMenuItemAltLocacao.setText("Alterar");
        jMenu4.add(jMenuItemAltLocacao);

        jMenuItemExcLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/key_delete.png"))); // NOI18N
        jMenuItemExcLocacao.setText("Excluir");
        jMenu4.add(jMenuItemExcLocacao);

        jMenuItemConLocacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/zoom.png"))); // NOI18N
        jMenuItemConLocacao.setText("Consultar");
        jMenu4.add(jMenuItemConLocacao);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1618, 847));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItemCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadClienteActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        AreaCadastrarClientePF pF = new AreaCadastrarClientePF();
        jDesktopPane1.add(pF);
        pF.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        jDesktopPane1.removeAll();
        AreaCadastrarClientePJ pJ = new AreaCadastrarClientePJ();
        jDesktopPane1.add(pJ);
        pJ.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        AreaCadastrarMotorista motorista = new AreaCadastrarMotorista();
        jDesktopPane1.add(motorista);
        motorista.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemCadastrarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarMarcaActionPerformed
        // TODO add your handling code here:
        AreaCadastrarMarca marca = new AreaCadastrarMarca();
        jDesktopPane1.add(marca);
        marca.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAddLocacao;
    private javax.swing.JMenuItem jMenuItemAddUsuario;
    private javax.swing.JMenuItem jMenuItemAddVeiculo;
    private javax.swing.JMenuItem jMenuItemAltCliente;
    private javax.swing.JMenuItem jMenuItemAltLocacao;
    private javax.swing.JMenuItem jMenuItemAltUsuario;
    private javax.swing.JMenuItem jMenuItemAltVeiculo;
    private javax.swing.JMenuItem jMenuItemCadCliente;
    private javax.swing.JMenuItem jMenuItemCadastrarMarca;
    private javax.swing.JMenuItem jMenuItemConCliente;
    private javax.swing.JMenuItem jMenuItemConLocacao;
    private javax.swing.JMenuItem jMenuItemConUsuario;
    private javax.swing.JMenuItem jMenuItemConVeiculo;
    private javax.swing.JMenuItem jMenuItemExcCliente;
    private javax.swing.JMenuItem jMenuItemExcLocacao;
    private javax.swing.JMenuItem jMenuItemExcUsuario;
    private javax.swing.JMenuItem jMenuItemExcVeiculo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
